apiVersion: v1
kind: Pod
metadata:
  name: psklsm-pod
spec:
  containers:
    - name: psklsm-container
      image: psklsm/hellok8s:v1
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"