apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-monitor
  namespace: monitoring
  labels:
    app: prometheus-monitor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prometheus-monitor
  template:
    metadata:
      labels:
        app: prometheus-monitor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: monitor
        image: prometheus-monitor:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: PROMETHEUS_URL
          value: "http://prometheus-operated:9090"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-monitor
  namespace: monitoring
  labels:
    app: prometheus-monitor
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: prometheus-monitor
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-monitor
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: prometheus-monitor
  endpoints:
  - port: "metrics"
    interval: 30s
    path: /metrics
  namespaceSelector:
    matchNames:
    - monitoring
