apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alert-manager
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: alert-manager
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
